# Generated by Django 4.1.3 on 2022-11-21 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('abreviatura', models.CharField(max_length=20)),
                ('aniofundacion', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Jugadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_pasaporte', models.IntegerField()),
                ('nombre', models.CharField(max_length=50)),
                ('nacionalidad', models.CharField(max_length=20)),
                ('edad', models.IntegerField()),
                ('posicion', models.CharField(max_length=50)),
                ('abr_posicion', models.CharField(max_length=20)),
                ('num_dorsal', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_pasaporte', models.IntegerField()),
                ('nombre', models.CharField(max_length=50)),
                ('nacionalidad', models.CharField(max_length=20)),
                ('edad', models.IntegerField()),
                ('cargo', models.CharField(max_length=50)),
                ('abr_cargo', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='torneo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
