# Generated by Django 4.1.3 on 2022-11-23 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugadores',
            name='equipo_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='equipo_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
