# Generated by Django 4.1.3 on 2022-11-24 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneo', '0002_jugadores_equipo_id_staff_equipo_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugadores',
            name='abr_cargo',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='jugadores',
            name='cargo',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='jugadores',
            name='abr_posicion',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='jugadores',
            name='num_dorsal',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='jugadores',
            name='posicion',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='staff',
            name='cargo',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
