# Generated by Django 4.1.3 on 2022-11-24 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneo', '0003_jugadores_abr_cargo_jugadores_cargo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugadores',
            name='num_dorsal',
            field=models.IntegerField(null=True),
        ),
    ]
